### ISSUE TITLE
about design

### ISSUE THREAD

**Issue by neuromagus** [SethSenpai/Tanuki#4]
Amazing keyboard. Really. After using HHKB - the best choice. But, I have questions:

Firstly - staggered, maybe better ortho? 
Secondly - need split this keyboard or not?

and latest question - really need any highlights :) ?

**Comment by SethSenpai** [comment]
Hey,
Thanks for the praise!

You're more than welcome to create a ortho and split version of the Tanuki, I personally don't like typing on ortho because I'm an old man but you're welcome to Fork the project and remix it.

I'm a bit confused what you mean with highlights?

**Comment by neuromagus** [comment]
> what you mean with highlights?

For touch-typing not needed any LEDs, IMO. I prefer Improved Dvorak... This is fixed xkb (in Linux) for keyboards, who did not have any QMK:

![ver1](https://user-images.githubusercontent.com/63796667/181907318-af716d22-9e9c-431b-9530-caac7a2c934a.jpg)

Do you think staggered better for typing? And what u think about this format? - https://github.com/foostan/crkbd

And last question. I very, very like Topre switches. Maybe possible create this keyboard with Topre switches?

P.S. Sorry for my English...

**Comment by SethSenpai** [comment]
> For touch-typing not needed any LEDs, IMO.

Ah alright, I put the LED's in to give a visual confirmation of the layer that you're on with your keyboard. I feel it's quite nice but you can just leave them out if you don't want them.

> Do you think staggered better for typing?

Depends on what you're used to. I learned typing on an ancient mechanical typewriter so staggered qwerty is just all I've known. 

> And what u think about this format?

Looks nice! I do a lot of CAD work so personally I think I'd like something that has the modifier keys easier to access without having your hands in typing mode.

> Maybe possible create this keyboard with Topre switches?

Yes this should totally work, _you_ will need to modify the pcb and plate a bunch. And need to find a place to source the topre "switches". Since they're so closely related to the layout of the pcb. Maybe a good place to start is to make a 4 key macropad with the topre switches first to get a handle on using them since they're quite a bit different from your standard switch.

> P.S. Sorry for my English...

No problem, you can only get better with practice!

**Comment by neuromagus** [comment]
>Maybe a good place to start is to make a 4 key macropad with the topre switches 

Thanks for amazing advice. Well, need a practice...
